name: DeployMaster

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: echo ref
      run: echo github.ref
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      if: github.ref == "master"
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY }} # 必須
        public-key: ${{ secrets.SSH_KEY_PUBLIC }} # 必須
        name: id_rsa # 省略可
    - name: ssh ec2 instance
      if: github.ref == "master"
      run: ssh -i "~/.ssh/id_rsa" -o StrictHostKeyChecking=no -t deploy@3.115.111.84 "cd nodetest; source ~/.nvm/nvm.sh; nohup npm start > out.log 2 > err.log&"

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      if: github.ref == "branch1"
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY_TOMITA_TEST }} # 必須
        public-key: ${{ secrets.SSH_KEY_PUBLIC_TOMITA_TEST }} # 必須
        name: id_rsa # 省略可
    - name: ssh ec2 instance
      if: github.ref == "branch1"
      run: ssh -i "~/.ssh/id_rsa" -o StrictHostKeyChecking=no -t deploy@13.230.179.120 "touch data.txt"
