name: only master branch
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1
      - name: composer install
        run: cd api ＆＆ composer install
      - name: add permission
        run: chmod -R g+w api ＆＆ sudo groupadd -f apache ＆＆ sudo chown -R :apache api
      - name: ssh key generate
        run: echo ”$SSH_PRIVATE_KEY” ＞ key ＆＆ chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      - name: rsync deploy
        run: ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ubuntu@ec2-3-115-111-84.ap-northeast-1.compute.amazonaws.com "touch data.txt"
