name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      env:
        SSH_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: echo $SSH_KEY > ~/data.txt
    - name: deploy
      run: ssh -i "~/data.txt" -o StrictHostKeyChecking=no ec2-user@18.176.58.235 "touch data.txt"
      
