name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: ssh -i "${{ secrets.SSH_KEY }}" ec2-user@ec2-52-69-15-5.ap-northeast-1.compute.amazonaws.com sh deploy.sh