name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_DATA: ${{secrets.SSH_KEY}}
    steps:
            - name: deploy
              run: echo SSH_DATA | vi data.txt
            - name: deploy2
              run: cat data.txt | echo -e $(cat)      
