name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: vi sshkey
      run: echo ${{secrets.SSH_KEY}} | data
    - name: run deploy script
      run: ssh -i "~/data" ec2-user@ec2-18-176-58-235.ap-northeast-1.compute.amazonaws.com "touch dddd"
