name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: echo $SSH_KEY > ~/data.pem
    - name: set permission
      run: chmod 600 ~/data.pem
    - name: deploy
      run: ssh -i "~/data.pem" -o StrictHostKeyChecking=no ec2-user@18.176.58.235 "touch data.txt"
      
