name: DeployMaster

on:
  push:
    branches:
      - branch1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with: # shimataro/ssh-key-actionに渡すパラメーター
        private-key: ${{ secrets.SSH_KEY_TOMITA_TEST }} # 必須
        public-key: ${{ secrets.SSH_KEY_PUBLIC_TOMITA_TEST }} # 必須
        name: id_rsa # 省略可
    - name: ssh ec2 instance
      run: ssh -i "~/.ssh/id_rsa" -o StrictHostKeyChecking=no -t deploy@13.230.179.120 "touch data.txt"
